### ISSUE TITLE
Upgrade status "UNKNOWN"

### ISSUE THREAD

**Issue by dsmrt** [flipboxfactory/keychain#3]
@darylknight found this 

Seems to be found on `admin/utilities/upgrade` (probably a later version of 3.0 in prep for 4.0 upgrades).

...

I'm still seeing "UNKNOWN" for the sub-plugin(?) that comes with this, "KeyChain". Is this also ready to go?

![image](https://user-images.githubusercontent.com/1250017/185611136-9ea676c9-79bb-4554-b6f3-58e7f40a7b6d.png)

_Originally posted by @darylknight in https://github.com/flipboxfactory/saml-sp/issues/169#issuecomment-1220576894_

**Comment by CreateSean** [comment]
So does this plugin work with Craft 4? 

Is it abandoned? are there plans to update for Craft 5?

**Comment by dsmrt** [comment]
Supports craft 4. We need to update for craft 5. We'll update this for consistency since this plugin is a dependency: https://github.com/flipboxfactory/saml-sp/issues/210

**Comment by CreateSean** [comment]
This is good news. Looking forward to the Craft 5 update

**Comment by dsmrt** [comment]
Check out new version 5.0.0: https://packagist.org/packages/flipboxfactory/keychain

🎉
